// src/templates/post.tsx
import * as React from 'react';
import { graphql, HeadFC, Link, PageProps } from 'gatsby';
import Layout from '../components/layout';
import kebabCase from 'lodash/kebabCase';
import { SEO } from '../components/seo';
import '../styles/github-markdown.css';
import '../styles/prism-nord.css';

const BlogPostTemplate = ({
  data, // this prop will be injected by the GraphQL query below.
}: PageProps<Queries.BlogPostTemplateQuery>) => {
  const { markdownRemark } = data; // data.markdownRemark holds your post data

  const frontmatter = markdownRemark?.frontmatter;
  return (
    <Layout>
      <div className="container-inner mx-auto my-8">
        <article>
          <h1 className="text-4xl font-bold leading-tight">{frontmatter?.title}</h1>
          <div className="text-xl text-gray-700 dark:text-gray-500">{frontmatter?.date}</div>
          <div className="text-sm text-gray-700 dark:text-gray-500 mb-4">{markdownRemark?.timeToRead} min read</div>
          <div className="flex mb-8 text-sm">
            {frontmatter?.tags?.map(tag => (
              <Link
                to={`/tag/${kebabCase(tag ?? '')}`}
                key={tag}
                className="bg-gray-300 rounded-full px-4 py-2 mr-4 text-brand-900 hover:bg-brand-300"
              >
                {tag}
              </Link>
            ))}
          </div>
          <div className="markdown-body mb-8" dangerouslySetInnerHTML={{ __html: markdownRemark?.html ?? '' }} />
          {(markdownRemark?.frontmatter?.references?.length ?? 0) > 0 && (
            <div className="mb-6 pt-6 border-t-1 border-gray-600">
              <h2 className="text-xl">References</h2>
              <ul className="list-disc list-inside">
                {frontmatter?.references?.map(
                  reference =>
                    reference && (
                      <li key={reference}>
                        <a
                          className="external mb-1 inline-block"
                          style={{ padding: '5px 0' }}
                          target="_blank"
                          rel="noreferrer"
                          href={reference.split('|')[0]}
                        >
                          {reference.split('|')[1]}
                        </a>
                      </li>
                    ),
                )}
              </ul>
            </div>
          )}
          <div className="mb-8 pt-2 border-t-3 border-double border-gray-600">
            <Link to="/" className="font-bold uppercase">
              Back to Blog
            </Link>
          </div>
        </article>
      </div>
    </Layout>
  );
};

export default BlogPostTemplate;

export const Head: HeadFC<Queries.BlogPostTemplateQuery> = ({ data }) => (
  <SEO title={data.markdownRemark?.frontmatter?.title}>
    <script type="application/ld+json">
      {JSON.stringify(
        {
          '@context': 'https://schema.org',
          '@type': 'BlogPosting',
          headline: data.markdownRemark?.frontmatter?.title,
          datePublished: data.markdownRemark?.frontmatter?.dateIso,
          dateModified: data.markdownRemark?.frontmatter?.dateIso,
          mainEntityOfPage: {
            '@type': 'WebPage',
            '@id': `https://chowson.github.io${data.markdownRemark?.frontmatter?.path}`,
          },
          author: [
            {
              '@type': 'Person',
              name: 'Chris Howson',
              url: 'https://github.com/chowson',
            },
          ],
          publisher: {
            '@type': 'Organization',
            name: 'chowson.github.io',
            logo: {
              '@type': 'ImageObject',
              url: 'https://chowson.github.io/images/logo.png',
            },
          },
          image: 'https://chowson.github.io/images/logo.png',
          description: data.markdownRemark?.frontmatter?.description,
        },
        null,
        2,
      )}
    </script>
  </SEO>
);

export const query = graphql`
  query BlogPostTemplate($id: String!) {
    markdownRemark(id: { eq: $id }) {
      frontmatter {
        title
        path
        date(formatString: "MMMM DD, YYYY")
        dateIso: date
        tags
        references
        description
      }
      html
      timeToRead
    }
  }
`;

// src/templates/Post.vue
<template>
  <Layout>
    <div class="container-inner mx-auto my-8">
      <article>
        <h1 class="text-4xl font-bold leading-tight">{{ $page.post.title }}</h1>
        <div class="text-xl text-gray-700 dark:text-gray-500">{{ $page.post.date }}</div>
        <div class="text-sm text-gray-700 dark:text-gray-500 mb-4">{{ $page.post.timeToRead }} min read</div>
        <div class="flex mb-8 text-sm">
          <g-link
            :to="tag.path"
            v-for="tag in $page.post.tags"
            :key="tag.id"
            class="bg-gray-300 rounded-full px-4 py-2 mr-4 text-brand-900 hover:bg-brand-300">
            {{ tag.title }}
          </g-link>
        </div>
        <div class="markdown-body mb-8" v-html="$page.post.content" />
        <div class="mb-6 pt-6 border-t-1 border-gray-600" v-if="$page.post.references.length > 0">
          <h2 class="text-xl">References</h2>
          <ul class="list-disc list-inside">
            <li v-for="reference in $page.post.references" :key="reference">
              <a class="external mb-1 inline-block" style="padding: 5px 0" target="_blank" rel="noreferrer" :href="reference.split('|')[0]">{{ reference.split("|")[1] }}</a>
            </li>
          </ul>
        </div>
        <div class="mb-8 pt-2 border-t-3 border-double border-gray-600">
          <g-link to="/" class="font-bold uppercase">Back to Blog</g-link>
        </div>
      </article>
    </div>
  </Layout>
</template>

<page-query>
query Post ($path: String!) {
  post: post (path: $path) {
    title
    description
    date (format: "MMMM D, Y")
    timeToRead
    content
    tags {
      title
      path
    }
    references
    path
  }
}
</page-query>

<script>
export default {
  metaInfo() {
    if(this.$page && this.$page.post)
    {
      var publishedDate = new Date(this.$page.post.date);
      var formattedPublishedDate = `${publishedDate.getFullYear()}-${("0" + publishedDate.getMonth()).slice(-2)}-${("0" + publishedDate.getDate()).slice(-2)}`;

      return {
        title: this.$page.post.title,
        meta: [
          { name: 'description', content: this.$page.post.description },
        ],
        script: [
          {
            innerHTML: JSON.stringify({
              "@context": "https://schema.org/",
              "@type": "BlogPosting",
              "mainEntityOfPage": {
                "@type": "WebPage",
                "@id": `https://chowson.github.io${this.$page.post.path}`
              },
              "headline": "headling",
              "author": {
                "@type": "Person",
                "name": "Chris Howson",
                "sameAs": "https://github.io/chowson"
              },
              "publisher": {
                "@type": "Organization",
                "name": "chowson.github.io",
                "logo": {
                  "@type": "ImageObject",
                  "url": "https://chowson.github.io/images/logo.png"
                }
              },
              "image": "https://chowson.github.io/images/logo.png",
              "dateCreated": formattedPublishedDate,
              "datePublished": formattedPublishedDate,
              "dateModified": formattedPublishedDate,
              "description": this.$page.post.description
            }),
            type: 'application/ld+json'
          }
        ]
      }
    }
  }
}
</script>

<style src="../css/github-markdown.css" />
