// src/pages/Index.vue
<template>
  <Layout>
    <hero />

    <div class="container-inner mx-auto py-16">
      <div v-for="post in $page.posts.edges" :key="post.id" class="post border-gray-400 border-b mb-12">
        <h2 class="text-3xl font-bold"><g-link :to="post.node.path" class="text-copy-primary">{{ post.node.title }}</g-link></h2>
        <div class="text-copy-secondary mb-4">
          <span>{{ post.node.date }}</span>
          <span> &middot; </span>
          <span>{{ post.node.timeToRead }} min read</span>
        </div>

        <div class="text-lg mb-4">
          {{ post.node.description }}
        </div>

        <div class="mb-8">
          <g-link :to="post.node.path" class="font-bold uppercase">Read More</g-link>
        </div>
      </div> <!-- end post -->

      <pagination-posts
        base="/blog"
        :totalPages="totalPageCount"
        :currentPage="1"
      />
    </div>
  </Layout>
</template>

<page-query>
query Posts ($page: Int) {
  posts: allPost (sortBy: "date", order: DESC, perPage: 5, page: $page) {
    totalCount
    pageInfo {
      totalPages
      currentPage
    }
    edges {
      node {
        id
        title
        date (format: "MMMM D, Y")
        description
        timeToRead
        path
      }
    }
  }
}
</page-query>

<script>
import PaginationPosts from '../components/PaginationPosts'

export default {
  metaInfo: {
    title: 'Home',
    links: [
      { rel: 'canonical', href: 'https://chowson.github.io' }
    ],
    script: [
      {
        innerHTML: JSON.stringify({
          "@context": "https://schema.org/",
          "@type": "WebSite",
          "name": "chowson.github.io",
          "url": "https://chowson.github.io"
        }),
        type: 'application/ld+json'
      }
    ]
  },
  components: {
    PaginationPosts
  },
  computed : {
    totalPageCount() {
      return Math.ceil(this.$page.posts.totalCount / 5);
    }
  }
}
</script>

// src/pages/index.tsx
import * as React from 'react';
import { graphql, HeadFC, Link, PageProps } from 'gatsby';
import Layout from '../components/layout';
import { SEO } from '../components/seo';
import Hero from '../components/hero';
import { PaginationPosts } from '../components/pagination-posts';

const IndexPage: React.FC<PageProps<Queries.IndexPageQuery>> = ({ data, pageContext }) => {
  return (
    <Layout>
      <Hero />

      <div className="container-inner mx-auto py-16">
        {data.allMarkdownRemark.nodes.slice(0, 5).map(post => (
          <div className="post border-gray-400 border-b mb-12" key={post.id}>
            <h2 className="text-3xl font-bold">
              <Link to={post.frontmatter?.path ?? '#'} className="text-copy-primary">
                {post.frontmatter?.title}
              </Link>
            </h2>
            <div className="text-copy-secondary mb-4">
              <span>{post.frontmatter?.date}</span>
              <span> &middot; </span>
              <span>{post.timeToRead} min read</span>
            </div>

            <div className="text-lg mb-4">{post.frontmatter?.description}</div>

            <div className="mb-8">
              <Link to={post.frontmatter?.path ?? '#'} className="font-bold uppercase">
                Read post
              </Link>
            </div>
          </div>
        ))}

        <PaginationPosts base="/blog" totalPages={Math.ceil(data.allMarkdownRemark.totalCount / 5)} currentPage={1} />
      </div>
    </Layout>
  );
};

export default IndexPage;

export const Head: HeadFC = () => (
  <SEO>
    <script type="application/ld+json">
      {JSON.stringify(
        {
          '@context': 'https://schema.org/',
          '@type': 'WebSite',
          name: 'chowson.github.io',
          url: 'https://chowson.github.io',
          image: 'https://chowson.github.io/images/logo.png',
        },
        null,
        2,
      )}
    </script>
  </SEO>
);

export const query = graphql`
  query IndexPage {
    allMarkdownRemark(sort: { frontmatter: { date: DESC } }) {
      totalCount
      nodes {
        id
        frontmatter {
          path
          date(formatString: "MMMM D, Y")
          title
          description
        }
        excerpt
        timeToRead
      }
    }
  }
`;
