// src/components/pagination-posts.tsx
import { Link } from 'gatsby';
import React from 'react';

type PaginationPostsProps = {
  base: string;
  totalPages: number;
  currentPage: number;
};

export const PaginationPosts = ({ base, currentPage, totalPages }: PaginationPostsProps) => {
  const previousPage = currentPage - 1;
  const nextPage = currentPage + 1;

  return (
    <nav className="flex justify-between text-xl items-center">
      {currentPage === 1 ? (
        <span></span>
      ) : (
        <Link rel="prev" to={previousPage === 1 ? '/' : `${base}/${previousPage}`}>
          &larr; Prev
        </Link>
      )}
      <div className="text-base">
        Page {currentPage} of {totalPages}
      </div>
      {currentPage < totalPages ? (
        <Link
          rel="next"
          to={`${base}/${currentPage + 1}`}
          className={currentPage === totalPages ? `text-gray-400 hover:text-gray-400 cursor-not-allowed` : ''}
        >
          Next &rarr;
        </Link>
      ) : (
        <span></span>
      )}
    </nav>
  );
};

// src/components/PaginationPosts.vue
<template>
  <nav class="flex justify-between text-xl items-center">
    <span v-if="!showPreviousPage"></span>
    <g-link
      v-else
      rel="prev"
      :to="previousPage"
      exact
      :class="{ 'text-gray-400 hover:text-gray-400 cursor-not-allowed': !showPreviousPage }">&larr; Prev</g-link>
    <div class="text-base">Page {{ currentPage }} of {{ totalPages }}</div>
    <g-link
      rel="next"
      :to="nextPage"
      active
      :class="{ 'text-gray-400 hover:text-gray-400 cursor-not-allowed': !showNextPage }">Next &rarr;</g-link>
  </nav>
</template>

<script>
export default {
  props: ['base', 'totalPages', 'currentPage'],
  computed: {
    showPreviousPage() {
      return this.currentPage !== 1
    },
    previousPage() {
      return [0, 1].includes(this.currentPage - 1)
        ? '/'
        : `${this.getBaseUrl}/${this.currentPage - 1}`;
    },
    showNextPage() {
      return this.currentPage !== this.totalPages
    },
    nextPage(currentPage, totalPages) {
      return this.totalPages > this.currentPage
        ? `${this.getBaseUrl}/${this.currentPage + 1}`
        : `${this.getBaseUrl}/${this.currentPage}`;
    },
    getBaseUrl() {
      return this.base.endsWith('/')
        ? this.base.replace(/\/$/, "")
        : this.base;
    }
  }
}
</script>
