// src/components/searchInput.tsx
import { Link, navigate } from 'gatsby';
import React, { useCallback, useEffect, useRef, useState } from 'react';

type IndexedPost = {
  title: string;
  description: string;
  path: string;
};

export const SearchInput = () => {
  const [searchValue, setSearchValue] = useState('');
  const [searchVisible, setSearchVisible] = useState(false);
  const [highlightedIndex, setHighlightedIndex] = useState(0);
  const searchIndex = useRef<IndexedPost[]>([]);
  const searchInput = useRef<HTMLInputElement>(null);
  const searchResults = useCallback(() => {
    const regex = new RegExp(`${searchValue}`, 'i');

    return searchIndex.current.filter(post => regex.test(post.title));
  }, [searchValue]);

  const searchFocusListener = () => {
    searchInput.current?.focus();
  };

  useEffect(() => {
    window.addEventListener('keyup', searchFocusListener);

    return () => window.removeEventListener('keyup', searchFocusListener);
  }, []);

  const reset = () => {
    setSearchValue('');
  };

  const onSearchFocus = () => {
    setSearchVisible(true);
    fetch('/search/posts.json')
      .then(data => data.json())
      .then(res => {
        searchIndex.current = res;
      });
  };

  const onKeyUp: React.KeyboardEventHandler<HTMLInputElement> = e => {
    if (e.key === 'ArrowUp') {
      if (highlightedIndex > 0) {
        setHighlightedIndex(highlightedIndex - 1);
      }
    } else if (e.key === 'ArrowDown') {
      if (highlightedIndex + 1 !== searchResults().length) {
        setHighlightedIndex(highlightedIndex + 1);
      }
    } else if (e.key === 'Enter') {
      navigate(searchResults()[highlightedIndex].path);
    }

    setTimeout(() => document.querySelector('.search-highlighted')?.scrollIntoView({ block: 'nearest' }), 1);
  };

  return (
    <div className="relative">
      <div className="relative w-80">
        <input
          ref={searchInput}
          type="text"
          placeholder='Search (Press  "/" to focus)'
          className="bg-background-form border border-gray-500 rounded-full px-4 pl-10 py-2 outline-none focus:border-brand-500 w-80"
          value={searchValue}
          autoComplete="off"
          onChange={e => setSearchValue(e.target.value)}
          onFocus={onSearchFocus}
          onKeyUp={onKeyUp}
        />
        <div className="absolute top-0 ml-3" style={{ top: '10px' }}>
          <svg fill="currentColor" className="text-gray-500 h-5 w-5" viewBox="0 0 24 24" width="24" height="24">
            <path
              className="heroicon-ui"
              d="M16.32 14.9l5.39 5.4a1 1 0 0 1-1.42 1.4l-5.38-5.38a8 8 0 1 1 1.41-1.41zM10 16a6 6 0 1 0 0-12 6 6 0 0 0 0 12z"
            ></path>
          </svg>
        </div>
        {searchValue.length > 0 && (
          <button className="absolute top-0 right-0 text-2xl mr-3 cursor-pointer text-gray-600 hover:text-gray-800 h-fit" onClick={reset}>
            &times;
          </button>
        )}
      </div>
      {searchValue.length > 0 && searchVisible && (
        <div
          className="normal-case absolute border left-0 right-0 w-108 max-w-full text-left mb-4 mt-2 rounded-lg shadow overflow-hidden z-10 overflow-y-auto"
          style={{ maxHeight: '32rem' }}
        >
          {searchResults().length > 0 ? (
            <div className="flex flex-col">
              {searchResults().map((a: IndexedPost, idx: number) => (
                <Link
                  to={a.path ?? '#'}
                  className={`bg-background-form border-b border-gray-400 text-xl cursor-pointer p-4 search-hover ${
                    highlightedIndex === idx && 'underline search-highlighted'
                  }`}
                  key={a.title ?? idx}
                >
                  {a.title}
                  <span className="block font-normal text-copy-primary text-sm my-1">{a.description}</span>
                </Link>
              ))}
            </div>
          ) : (
            <div className="bg-background-form font-normal w-full border-b cursor-pointer p-4">
              <p className="my-0">
                No results for '<strong>{searchValue}</strong>'
              </p>
            </div>
          )}
        </div>
      )}
    </div>
  );
};

// src/components/SearchInput.vue
<template>
  <div class="relative">
    <search-focus @keyup="focusSearch"></search-focus>

    <div class="relative w-80">
      <input
        type="text"
        placeholder="Search (Press  &quot;/&quot; to focus)"
        class="bg-background-form border border-gray-500 rounded-full px-4 pl-10 py-2 outline-none focus:border-brand-500 w-80"
        v-model="query"
        @input="softReset"
        @keyup="performSearch"
        @keyup.esc="searchResultsVisible = false"
        @keydown.up.prevent="highlightPrev"
        @keydown.down.prevent="highlightNext"
        @keyup.enter="gotoLink"
        @blur="searchResultsVisible = false"
        @focus="searchResultsVisible = true"
        ref="search"
      >
      <div class="absolute top-0 ml-3" style="top:10px">
        <svg fill="currentColor" class="text-gray-500 h-5 w-5" viewBox="0 0 24 24" width="24" height="24"><path class="heroicon-ui" d="M16.32 14.9l5.39 5.4a1 1 0 0 1-1.42 1.4l-5.38-5.38a8 8 0 1 1 1.41-1.41zM10 16a6 6 0 1 0 0-12 6 6 0 0 0 0 12z"></path></svg>
      </div>
      <div
        v-if="query.length > 0"
        class="absolute top-0 right-0 text-2xl mr-3 cursor-pointer text-gray-600 hover:text-gray-800"
        @click="reset"
      >
        &times;
      </div>
    </div>
    <transition name="fade">
      <div v-if="query.length > 0 && searchResultsVisible" class="normal-case absolute border left-0 right-0 w-108 max-w-full text-left mb-4 mt-2 rounded-lg shadow overflow-hidden z-10 overflow-y-auto" style="max-height: 32rem">
        <div class="flex flex-col" ref="results">
          <a
            v-for="(post, index) in results"
            :key="index"
            :href="post.item.path"
            @click="reset"
            class="bg-background-form border-b border-gray-400 text-xl cursor-pointer p-4 search-hover"
            :class="{ 'search-highlighted' : index === highlightedIndex }"
          >
            {{ post.item.title }}

            <span class="block font-normal text-copy-primary text-sm my-1">{{ post.item.description }}</span>
          </a>

          <div v-if="results.length === 0" class="bg-background-form font-normal w-full border-b cursor-pointer p-4">
            <p class="my-0">No results for '<strong>{{ query }}</strong>'</p>
          </div>
        </div>
      </div>
    </transition>
  </div>
</template>


<static-query>
query Search {
  allPost {
    edges {
      node {
        id
        path
        title
        description
        headings {
          depth
          value
          anchor
        }
      }
    }
  }
}
</static-query>

<script>
import SearchFocus from './SearchFocus'

export default {
  components: {
    SearchFocus,
  },
  computed: {
    pages () {
      let result = [];
      const allPost = this.$static.allPost.edges.map(edge => edge.node);
      allPost.forEach(page => {
        result.push({
          path: page.path,
          title: page.title,
          description: page.description
        });
      });
      return result;
    }
  },
  data() {
    return {
      query: '',
      results: [],
      highlightedIndex: 0,
      searchResultsVisible: false,
      options: {
        shouldSort: true,
        includeMatches: true,
        threshold: 0.5,
        location: 0,
        distance: 500,
        maxPatternLength: 32,
        minMatchCharLength: 1,
        keys: ['title', 'description']
      }
    }
  },
  methods: {
    reset() {
      this.query = ''
      this.highlightedIndex = 0
    },
    softReset() {
      this.highlightedIndex = 0
      this.searchResultsVisible = true
    },
    performSearch() {
      this.$search(this.query, this.pages, this.options).then(results => {
        this.results = results
      })
    },
    highlightPrev() {
      if (this.highlightedIndex > 0) {
        this.highlightedIndex = this.highlightedIndex - 1
        this.scrollIntoView()
      }
    },
    highlightNext() {
      if (this.highlightedIndex < this.results.length - 1) {
        this.highlightedIndex = this.highlightedIndex + 1
        this.scrollIntoView()
      }
    },
    scrollIntoView() {
      this.$refs.results.children[this.highlightedIndex].scrollIntoView({ block: 'nearest' })
    },
    gotoLink() {
      if (this.results[this.highlightedIndex]) {
        window.location = this.results[this.highlightedIndex].item.path
      }
    },
    focusSearch(e) {
      if (e.key === '/') {
        this.$refs.search.focus()
      }
    }
  }
}
</script>

<style scoped>
  .fade-enter-active, .fade-leave-active {
    transition: opacity .2s;
  }
  .fade-enter, .fade-leave-to {
    opacity: 0;
  }
</style>
